// This source file was auto-generated by ClassMate++
// Created: 15 Apr 2012 8:57:30 pm
// Copyright (c) 2012, HurleyWorks

#include "berserkpch.h"
#include "IMaster.h"
// #include "../modules/Modules.h"

// ctor
IMaster::IMaster (GlobalFunc* const global, const std::string& pluginName) :
    global_ (global),
    pluginName (pluginName)

{
    LOG (DBUG) << _FN_;
}

// dtor
IMaster::~IMaster()
{
    LOG (DBUG) << _FN_;
}

// onMasterEvent
double IMaster::onMasterEvent (LWInstance, const LWMasterAccess* access)
{
    return 0.0f;
}

// masterFlags
unsigned int IMaster::masterFlags (LWInstance)
{
    return LWMAST_SCENE | LWMASTF_RECEIVE_NOTIFICATIONS | LWMASTF_RECEIVE_NOTIFICATIONS_MESHPOINTS;
}

// copy
LWError IMaster::copy (LWInstance dest, LWInstance src)
{
    return nullptr;
}

// describe
const char* IMaster::describe (LWInstance inst)
{
    return pluginName.c_str();
}

// destroy
void IMaster::destroy (LWInstance inst)
{
    LOG (DBUG) << _FN_;

    delete this;
}

// load
LWError IMaster::load (LWInstance inst, const LWLoadState* load)
{
    LOG (DBUG) << _FN_;

    return nullptr;
}

// save
LWError IMaster::save (LWInstance inst, const LWSaveState* save)
{
    LOG (DBUG) << _FN_;

    return nullptr;
}

// changeID
void IMaster::changeID (LWInstance, const LWItemID* itemID)
{
    LOG (DBUG) << _FN_;
}

// useItems
const LWItemID* IMaster::useItems (LWInstance inst)
{
    LOG (DBUG) << _FN_;
    return nullptr;
}
