// This source file was auto-generated by ClassMate++
// Created: 18 Feb 2020 6:02:06 pm
// Copyright (c) 2020, HurleyWorks

#include "berserkpch.h"
#include "LWModule.h"

bool LWModule::init(GlobalFunc* const g)
{
	lw.init(g);
	return false;
}

