// This source file was auto-generated by ClassMate++
// Created: 8 May 2011 5:48:42 am
// Copyright (c) 2011, HurleyWorks

#include "berserkpch.h"
#include "LWMsg.h"

// ctor
LWMsg::LWMsg()
    : global_(nullptr),
      msg_(nullptr),
      msgVer_(0)
{	
	
}

// dtor
LWMsg::~LWMsg ()
{	
   
}

void LWMsg::init(GlobalFunc * const g)
{
	global_ = g;
	debug_assert(global_);

	msg_ = getCompatibleVersion<LWMessageFuncs>(LWMESSAGEFUNCS_GLOBAL, global_, msgVer_);
	debug_assert(msg_);
}

void LWMsg::info( const char * line1, const char * line2)
{
    if(msg_)
        msg_->info(line1, line2);
}

void LWMsg::error( const char * line1, const char * line2)
{
    if(msg_)
        msg_->error(line1, line2);
}

void LWMsg::warning( const char * line1, const char * line2)
{
    if(msg_)
        msg_->warning(line1, line2);
}
