// This header file was auto-generated by ClassMate++
// Created: 8 May 2011 5:48:42 am
// Copyright (c) 2011, HurleyWorks

#pragma once

#include "LWsdk.h"

class LWMsg
{
 public:
    LWMsg();
    ~LWMsg();

    void init (GlobalFunc* const g);

    void info (const char* line1, const char* line2 = nullptr);
    void error (const char* line1, const char* line2 = nullptr);
    void warning (const char* line1, const char* line2 = nullptr);

 private:
    GlobalFunc* global_;
    LWMessageFuncs* msg_;
    int msgVer_;
};
