// This header file was auto-generated by ClassMate++
// Created: 16 Mar 2018 6:45:07 pm
// Copyright (c) 2018, HurleyWorks

#pragma once

class LWPlugin
{
 public:
    LWPlugin() = default;
    ~LWPlugin() = default;

 private:
    GlobalFunc* global_;
    LWServerInfo* pluginInfo_ = nullptr;

}; // end class LWPlugin
