// This header file was auto-generated by ClassMate++
// Created: 19 Aug 2009 6:49:19 am
// Copyright (c) 2009, HurleyWorks

#pragma once

#include "Control.h"

class Bool : public Control
		/// and responsibilty of class Bool
{

 public:
	Bool (ControlType type, const std::string & title, int width = 0);
		/// Creates a Bool instance

	~Bool ();
		/// Destroys a Bool instance

	std::string getTitle () const;

	ControlType getType () const;

 private:
	ControlType type_;
	std::string title_;

}; // end class Bool
