// This source file was auto-generated by ClassMate++
#include "berserkpch.h"
#include "Bool.h"
// Created: 19 Aug 2009 6:49:19 am
// Copyright (c) 2009, HurleyWorks

// ctor
Bool::Bool (ControlType type, const std::string & title,int width)
	: type_(type),
	  title_(title)
{

	switch (type)
	{
		case ControlType::BoolControl:
			desc.type = LWT_BOOLEAN;
			break;

		case ControlType::BoolButtonControl:
			if( width == 0 )
			{
				desc.type = LWT_BOOLEAN;
			}
			else if( width > 0 )
			{
				desc.type = LWT_AREA;
				desc.area.width = width;
				desc.area.height = 0;
			}
			break;

		default:
			break;
	};
}

// dtor
Bool::~Bool ()
{
}

// getTitle
std::string Bool::getTitle () const
{

	return title_;
}

// getType
ControlType Bool::getType () const
{

	return type_;
}


