// This source file was auto-generated by ClassMate++
#include "berserkpch.h"
#include "Choice.h"
// Created: 19 Aug 2009 6:49:19 am
// Copyright (c) 2009, HurleyWorks

// ctor
Choice::Choice (ControlType type,
                const char ** choices, 
                const std::string & title,
				int width)
	: type_(type),
	  title_(title)
{

	desc.type = LWT_CHOICE;
	desc.choice.items = choices;
	
	switch (type)
	{
		case ControlType::ChoiceControl:
			desc.choice.vertical = MX_HCHOICE;
			break;

		case ControlType::PopupControl:
			desc.choice.vertical = width;
			break;

		case ControlType::PopDownControl:
			desc.choice.vertical = MX_POPUP;
			break;

		case ControlType::TabChoiceControl:
			desc.choice.vertical = MX_HCHOICE;
			break;

		default:
			break;
	};
}

// dtor
Choice::~Choice ()
{
}

// getTitle
std::string Choice::getTitle () const
{

	return title_;
}

// getType
ControlType Choice::getType () const
{

	return type_;
}



