// This header file was auto-generated by ClassMate++
// Created: 19 Aug 2009 6:49:19 am
// Copyright (c) 2009, HurleyWorks

#pragma once

#include "Control.h"

class Choice : public Control
		/// and responsibilty of class Choice
{

 public:
	Choice (ControlType type, const char ** choices, const std::string & title, int width = 0);
		/// Creates a Choice instance

	~Choice ();
		/// Destroys a Choice instance

	std::string getTitle () const;

	ControlType getType () const;

 private:
	ControlType type_;
	std::string title_;

}; // end class Choice
