// This header file was auto-generated by ClassMate++
// Created: 19 Aug 2009 6:49:19 am
// Copyright (c) 2009, HurleyWorks

#pragma once

#include "Control.h"

class CustomPopup : public Control
		/// and responsibilty of class CustomPopup
{

 public:
	CustomPopup (const std::string & title, 
				int width, 
				LWNameCallback nameCallback,
				LWCountCallback countCallback);
		/// Creates a CustomPopup instance

	~CustomPopup ();
		/// Destroys a CustomPopup instance

	std::string getTitle () const;

	ControlType getType () const;

 private:
	std::string title_;

}; // end class CustomPopup


class CustomPopDown : public Control
		/// and responsibilty of class CustomPopDown
{

 public:
	CustomPopDown (const std::string & title, 
				int width, 
				LWNameCallback nameCallback,
				LWCountCallback countCallback);
		/// Creates a CustomPopDown instance

	~CustomPopDown ();
		/// Destroys a CustomPopDown instance

	std::string getTitle () const;

	ControlType getType () const;

 private:
	std::string title_;

}; // end class CustomPopDown
