// This source file was auto-generated by ClassMate++
#include "berserkpch.h"
#include "CustomPopup.h"
// Created: 19 Aug 2009 6:49:19 am
// Copyright (c) 2009, HurleyWorks

// ctor
CustomPopup::CustomPopup (const std::string & title, 
						  int width, 
						  LWNameCallback nameCallback,
						  LWCountCallback countCallback)
	: title_(title)
{

	desc.type = LWT_POPUP;
	desc.popup.width = width;
	desc.popup.nameFn = nameCallback;
	desc.popup.countFn = countCallback;
}

// dtor
CustomPopup::~CustomPopup ()
{
}

// getTitle
std::string CustomPopup::getTitle () const
{

	return title_;
}

// getType
ControlType CustomPopup::getType () const
{

	return ControlType::CustomPopupControl;
}


// ctor
CustomPopDown::CustomPopDown (const std::string & title, 
						  int width, 
						  LWNameCallback nameCallback,
						  LWCountCallback countCallback)
	: title_(title)
{

	desc.type = LWT_POPUP;
	desc.popup.width = width;
	desc.popup.nameFn = nameCallback;
	desc.popup.countFn = countCallback;
}

// dtor
CustomPopDown::~CustomPopDown ()
{
}

// getTitle
std::string CustomPopDown::getTitle () const
{

	return title_;
}

// getType
ControlType CustomPopDown::getType () const
{

	return ControlType::CustomPopdownControl;
}
