// This source file was auto-generated by ClassMate++
#include "berserkpch.h"
#include "IO.h"
// Created: 16 Aug 2009 4:17:19 pm
// Copyright (c) 2009, HurleyWorks

// ctor
IO::IO (ControlType type, int width, const std::string & title)
	: type_(type),
	  title_(title)
{

	desc.type = LWT_STRING;
	desc.string.width = width;
}

// dtor
IO::~IO ()
{
}

// getTitle
std::string IO::getTitle () const
{

	return title_;
}

// getType
ControlType IO::getType () const
{

	return type_;
}




