// This header file was auto-generated by ClassMate++
// Created: 16 Aug 2009 4:17:19 pm
// Copyright (c) 2009, HurleyWorks

#pragma once

#include "Control.h"

class IO : public Control
		/// and responsibilty of class IO
{

 public:
	IO (ControlType type, int width, const std::string & title = "File");
		/// Creates a IO instance

	~IO ();
		/// Destroys a IO instance

	std::string getTitle () const;

	ControlType getType () const;

 private:
    ControlType type_;
	std::string title_;

}; // end class IO
