// This source file was auto-generated by ClassMate++
#include "berserkpch.h"
#include "ItemList.h"
// Created: 16 Aug 2009 8:36:38 am
// Copyright (c) 2009, HurleyWorks

// ctor
ItemList::ItemList (int width,
				    const std::string& title,
				    GlobalFunc * const global,
				    const LWType & type)
{

	desc.type = LWT_LWITEM;
	desc.lwitem.global = (void*)(global);
	desc.lwitem.itemType = type;
	desc.lwitem.list = nullptr;
	desc.lwitem.count = 0;
	desc.lwitem.width = width;
}

// dtor
ItemList::~ItemList ()
{
}

// getTitle
std::string ItemList::getTitle () const
{

	return title_;
}

// getType
ControlType ItemList::getType () const
{

	return ControlType::LWListControl;
}


// ctor
ItemPickList::ItemPickList (int width,
							const std::string& title,
							GlobalFunc * const global,
							const LWType & type)
{

	desc.type = LWT_LWITEM;
	desc.lwitem.global = (void*)(global);
	desc.lwitem.itemType = type;
	desc.lwitem.list = nullptr;
	desc.lwitem.count = 0;
	desc.lwitem.width = width;
}

// dtor
ItemPickList::~ItemPickList ()
{
}

// getTitle
std::string ItemPickList::getTitle () const
{

	return title_;
}

// getType
ControlType ItemPickList::getType () const
{

	return ControlType::LWPickListControl;
}


