// This header file was auto-generated by ClassMate++
// Created: 16 Aug 2009 8:36:38 am
// Copyright (c) 2009, HurleyWorks

#pragma once

#include "Control.h"

class ItemList : public Control
		/// and responsibilty of class ItemList
{

 public:
	ItemList (int width,
			  const std::string& title,
			  GlobalFunc * const global,
			  const LWType & type);
		/// Creates a ItemList instance

	~ItemList ();
		/// Destroys a ItemList instance

	std::string getTitle () const;

	ControlType getType () const;

 private:
	ControlType type_;
	std::string title_;

}; // end class ItemList


class ItemPickList : public Control
		/// and responsibilty of class ItemPickList
{

 public:
	ItemPickList (int width,
			      const std::string& title,
			      GlobalFunc * const global,
			      const LWType & type);
		/// Creates a ItemPickList instance

	~ItemPickList ();
		/// Destroys a ItemPickList instance

	std::string getTitle () const;

	ControlType getType () const;

 private:
	ControlType type_;
	std::string title_;

}; // end class ItemPickList
