// This source file was auto-generated by ClassMate++
#include "berserkpch.h"
#include "PanButton.h"
// Created: 14 Aug 2009 7:10:36 pm
// Copyright (c) 2009, HurleyWorks

// ctor
Button::Button (const std::string& title, int width)
	: title_(title)
{

	if( width )
	{
		desc.type = LWT_AREA;
		desc.area.width = width;
		desc.area.height = 0;
	}
	else
		desc.type = LWT_INTEGER;
}

// dtor
Button::~Button ()
{
}

// getType
ControlType Button::getType () const
{

	return ControlType::ButtonControl;
}

// getTitle
std::string Button::getTitle () const
{

	return title_;
}


