// This header file was auto-generated by ClassMate++
// Created: 14 Aug 2009 7:10:36 pm
// Copyright (c) 2009, HurleyWorks

#pragma once

#include "Control.h"

// if this file is named Button.h, there's a link error when
// clients try to use the Button object. I think it's because
// there already exists a Button.h in the XPanels section and
// the #pragma once include guard keeps this one from being
// included

class Button : public Control
		/// and responsibilty of class Button
{

 public:
	 Button (const std::string& title = "Button", int width = 0);
		/// Creates a Button instance

	~Button ();
		/// Destroys a Button instance

	ControlType getType () const;

	std::string getTitle () const;
		
 private:
	std::string title_;

}; // end class Button
