// This source file was auto-generated by ClassMate++
#include "berserkpch.h"
#include "PanEdit.h"
// Created: 15 Aug 2009 5:46:04 pm
// Copyright (c) 2009, HurleyWorks

// ctor
Edit::Edit (ControlType type, const std::string& title, int width)
	: type_(type),
	  title_(title)
{

	switch (type)
	{
		case ControlType::NumControl:
			desc.type = LWT_INTEGER;
			break;

		case ControlType::VecControl:
			desc.type = LWT_VINT;
			break;

		case ControlType::FloatControl:
			desc.type = LWT_FLOAT;
			break;

		case ControlType::EditControl:
		case ControlType::InfoControl:
			desc.type = LWT_STRING;
			desc.string.width = width;
			break;
	}
}

// dtor
Edit::~Edit ()
{
}

// getTitle
std::string Edit::getTitle () const
{

	return title_;
}

// getType
ControlType Edit::getType () const
{

	return type_;
}


