// This header file was auto-generated by ClassMate++
// Created: 15 Aug 2009 9:10:09 pm
// Copyright (c) 2009, HurleyWorks

#pragma once

#include "Control.h"

class XPanCtrl : public Control
		/// and responsibilty of class XPanCtrl
{

 public:
	XPanCtrl (LWXPanelID xpanel, const std::string & title = "");
		/// Creates a XPanCtrl instance

	~XPanCtrl ();
		/// Destroys a XPanCtrl instance

	std::string getTitle () const;

	ControlType getType () const;

 private:
	std::string title_;

}; // end class XPanCtrl
